### ISSUE TITLE
Trying to build a project with your action, it finishes so fast and no image is created

### ISSUE THREAD

**Issue by izanaj** [iloveitaly/github-action-nixpacks#2]
`  - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ttl.sh
          username: "dummy"
          password: "dummy"

      - name: Extract Tag Name
        run: |
          # Extracts only the tag name (e.g., refs/tags/v1.0.0 -> v1.0.0)
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          echo "Tag name is $TAG_NAME"
          
          # Make TAG_NAME available to later steps
          echo "IMAGE_NAME=bla-bla-$TAG_NAME" >> $GITHUB_ENV

      - name: Build and push Docker images
        uses: iloveitaly/github-action-nixpacks@main
        with:
          push: true
          tags: |
            ttl.sh/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}`

<img width="1101" alt="image" src="https://github.com/user-attachments/assets/b637926c-196e-41f3-8242-2eba558b5199">

**Comment by mjamro** [comment]
It' doesn't work when no platform is specifed

The script does this:
```
if [ "${#PLATFORMS[@]}" -gt 1 ]; then
  build_and_push_multiple_architectures
elif [ -n "$PLATFORMS" ]; then
  build_and_push
fi
```

And with no platform specifed it somehow fells out of both if/elif 

As a workaround you can do:
 
```
          platforms: "linux/amd64,linux/amd64"
```

This basically runs the same build twice but it forces `build_and_push_multiple_architectures`.

**Comment by izanaj** [comment]
Thanks a lot, I missed this

**Comment by izanaj** [comment]
This does not work for me since it does not count for tags I provide but it generates in --tag ghcr.io/myrepo:linux-amd64

more here -> https://github.com/iloveitaly/github-action-nixpacks/blob/19e1c03c268713eed3857e6e65d6a384a5dd9bca/entrypoint.sh#L151 

Workaround is just to add one platform
